#ifndef MESSAGETYPE_H
#define MESSAGETYPE_H


#define SERVERID 0

#define LOGINEVENTGROUP 0x0
#define REQINFOGROUP 0x1
#define CHANGEINFOGROUP 0x2
#define REQUDPEVENTGROUP 0x3
#define UDPEVENTGROUP 0xff

#define RESUDPREQGROUP 0xfffc
#define RESCHANGEGROUP 0xfffd
#define RESINFOGROUP 0xfffe
#define SYSRESEVENTGROUP 0xffff



//0x0
#define LOGINACTION 0x0


//0x1
#define REQUSERINFOACTION 0x0
#define REQFRIENDSGROUPACTION 0x1
#define REQFRIENDSACTION 0x2



//0x2
#define CHANGEFRIENDOTHERNAMEACTION 0x0
#define ADDFRIENDSGROUPACTION 0x1
#define DELFRIENDSACTION 0x2
#define CHANGEFRIENDSGROUPACTION 0x3

//0x3
#define REQUDPCHATACTION 0x0
#define REQCLOSEUDPCHATACTION 0x1
#define REQUDPCHATSUCCESSACTION 0x2


//0xff
#define UDPADDENDPOINT 0x0
#define UDPTRANSFERMSG 0x1


//0xfffc
#define RESREADYUDPCHATSENDCODE 0x0
#define RESCLOSEUDPCHATCODE 0x1


//0xfffd
#define RESCHANGEFRIENDOTHERNAMECODE 0x0
#define RESADDFRIENDSGROUPCODE 0x1
#define RESDELFRIENDSCODE 0x2
#define RESCHANGEFRIENDSGROUPCODE 0x3


//0xfffe
#define RESUSERINFOCODE 0x0




//0xffff
#define SYSRESSUCCESSCODE 0x0
#define SYSRESERRORCODE 0xffff




#define MESSAGETYPE(t1, t2) (((t1) << 16) | (t2))
#define TYPEGROUP(t) ((t) >> 16)
#define TYPEACTION(t) ((t) & 0xffff)



#endif // MESSAGETYPE_H
